language: python
python:
  - "3.6"

sudo: true

install:
  - pip install ansible jmespath

script:
  - run.sh

#services:
#  - docker

#before_script:
#  - docker build -t mathieucoavoux/ansible_jenkins .

#script:
#  - docker run mathieucoavoux/ansible_jenkins