---
jenkins_version: "2.164.1"
jenkins_masters:
  - name: "master1"
    hostname: "master1"
    http_port: "8081"
    default_channel: "http"

jenkins_plugins:
  - name: "git"
    version: "3.9.3"
  - name: "configuration-as-code"
    version: "1.11"
  - name: "configuration-as-code-support"
    version: "1.11"
  - name: "job-dsl"
    version: "1.72"
  - name: "audit-trail" #Keep a log of who performed particular Jenkins operations, such as configuring jobs.
    version: "2.4"
  - name: "plain-credentials"
    version: "1.5"
  - name: "cloudbees-folder"
    version: "6.8"

jenkins_root_folder: "Admins"

filesystems:
  - name: "log"
    path: "/var/log/jenkins"
  - name: "etc"
    path: "/opt/jenkins/etc"
  - name: "etc_init"
    path: "/opt/jenkins/etc/init.d"
  - name: "etc_conf"
    path: "/opt/jenkins/etc/conf"
  - name: "etc_bin"
    path: "/opt/jenkins/etc/bin"
  - name: "etc_sysconfig"
    path: "/opt/jenkins/etc/sysconfig"
  - name: "cache"
    path: "/opt/jenkins/cache"
  - name: "home"
    path: "/opt/jenkins/home"
  - name: "var_run"
    path: "/var/run"
  - name: "tmp"
    path: "/opt/jenkins/tmp"
  - name: "user_home"
    path: "/home/ec2-user"

jenkins_credential:
  credential: "Core credential"
  path: "/configuration/jenkins_masters/aws_demo/secrets.yml"

jvm_configuration:
  launch_user: "ec2-user"
  launch_group: "ec2-user"
  debug_level: 5
  enable_access_log: "no"
  handler_max: 100
  handler_idle: 20
  suffix_url: "/jenkins"

maintenance_windows:
  - name: "Monday maintenance"
    type: "weekday"
    day: "Monday"
    start_time: "02:00:00"
    end_time: "03:00:00"
  - name: "Last sunday maintenance"
    type: "weekdayofmonth"
    day: "Sunday"
    keyword: "last"
    start_time: "08:00:00"
    end_time: "20:00:00"